"""Generated by Queron App from notebook cells. Do not edit by hand."""

import queron


@queron.postgres.ingress(
    config='PostGres',
    name='sql_78',
    out='policy_core',
    sql="""

SELECT
    p.policy_id,
    policy_number,
    product_line,
    underwriting_company,
    status,
    effective_date,
    expiration_date,
    written_premium,
    deductible_amount,
    billing_plan,
    agent_code,
    risk_state
FROM {{ queron.source("pg_policy") }} p
    """,
)
def sql_78():
    pass

@queron.postgres.ingress(
    config='PostGres',
    name='sql_79',
    out='policy_coverage',
    sql="""

SELECT
    coverage_id,
    policy_id,
    coverage_code,
    coverage_name,
    coverage_limit AS coverage_limit1,
    deductible_amount,
    premium_amount,
    is_optional
FROM {{ queron.source("pg_coverage") }}
    """,
)
def sql_79():
    pass

@queron.postgres.ingress(
    config='PostGres',
    name='sql_81',
    out='policy_claim',
    sql="""

SELECT
    claim_id,
    claim_number,
    policy_id,
    loss_date,
    reported_date,
    claim_status,
    loss_cause,
    reserve_amount,
    paid_amount,
    claim_state,
    adjuster_name,
    closed_date
FROM {{ queron.source("pg_claim") }}
    """,
)
def sql_81():
    pass

@queron.db2.ingress(
    config='LOOMDB@localhost',
    name='sql_83',
    out='customer_policy_link',
    sql="""

SELECT
    POLICY_KEY,
    POLICY_NUMBER,
    PERSON_ID,
    RELATIONSHIP_ROLE,
    EFFECTIVE_DATE,
    EXPIRATION_DATE,
    PREFERRED_CONTACT_CHANNEL
FROM {{ queron.source("db2_policy") }}
    """,
)
def sql_83():
    pass

@queron.db2.ingress(
    config='LOOMDB@localhost',
    name='sql_85',
    out='customer_person',
    sql="""

SELECT
    PERSON_ID,
    CUSTOMER_NUMBER,
    FIRST_NAME,
    LAST_NAME,
    BIRTH_DATE,
    OCCUPATION,
    ANNUAL_INCOME,
    PREFERRED_LANGUAGE
FROM {{ queron.source("db2_person") }}
    """,
)
def sql_85():
    pass

@queron.db2.ingress(
    config='LOOMDB@localhost',
    name='sql_87',
    out='customer_address',
    sql="""

SELECT
    PERSON_ID,
    ADDRESS_TYPE,
    ADDRESS_LINE1,
    CITY,
    STATE_CODE,
    POSTAL_CODE,
    COUNTRY_CODE,
    IS_PRIMARY
FROM {{ queron.source("db2_address") }}
WHERE IS_PRIMARY = 1
    """,
)
def sql_87():
    pass

@queron.db2.ingress(
    config='LOOMDB@localhost',
    name='sql_89',
    out='customer_phone',
    sql="""

SELECT
    PERSON_ID,
    PHONE_TYPE,
    PHONE_NUMBER,
    IS_PRIMARY
FROM {{ queron.source("db2_phone") }}
WHERE IS_PRIMARY = 1
    """,
)
def sql_89():
    pass

@queron.db2.ingress(
    config='LOOMDB@localhost',
    name='sql_99',
    out='customer_email',
    sql="""

SELECT
    PERSON_ID,
    EMAIL_TYPE,
    EMAIL_ADDRESS,
    IS_PRIMARY
FROM {{ queron.source("db2_email") }}
WHERE IS_PRIMARY = 1
    """,
)
def sql_99():
    pass

@queron.model.sql(
    name='sql_97',
    out='customer_profile',
    materialized='artifact',
    query="""

SELECT
    cp.POLICY_NUMBER AS policy_number,
    cp.PERSON_ID AS person_id,
    p.CUSTOMER_NUMBER AS customer_number,
    p.FIRST_NAME AS first_name,
    p.LAST_NAME AS last_name,
    p.BIRTH_DATE AS birth_date,
    p.OCCUPATION AS occupation,
    p.ANNUAL_INCOME AS annual_income,
    p.PREFERRED_LANGUAGE AS preferred_language,
    a.ADDRESS_LINE1 AS address_line1,
    a.CITY AS city,
    a.STATE_CODE AS state_code,
    a.POSTAL_CODE AS postal_code,
    ph.PHONE_NUMBER AS phone_number,
    e.EMAIL_ADDRESS AS email_address,
    cp.PREFERRED_CONTACT_CHANNEL AS preferred_contact_channel
FROM {{ queron.ref("customer_policy_link") }} cp
JOIN {{ queron.ref("customer_person") }} p
  ON cp.PERSON_ID = p.PERSON_ID
LEFT JOIN {{ queron.ref("customer_address") }} a
  ON cp.PERSON_ID = a.PERSON_ID
LEFT JOIN {{ queron.ref("customer_phone") }} ph
  ON cp.PERSON_ID = ph.PERSON_ID
LEFT JOIN {{ queron.ref("customer_email") }} e
  ON cp.PERSON_ID = e.PERSON_ID
    """,
)
def sql_97():
    pass

@queron.model.sql(
    name='sql_95',
    out='coverage_summary',
    materialized='artifact',
    query="""

SELECT
    policy_id,
    COUNT(*) AS coverage_count,
    SUM(premium_amount) AS total_coverage_premium,
    MAX(CASE WHEN is_optional THEN 1 ELSE 0 END) AS has_optional_coverage
FROM {{ queron.ref("policy_coverage") }}
GROUP BY policy_id
    """,
)
def sql_95():
    pass

@queron.model.sql(
    name='sql_93',
    out='claim_summary',
    materialized='artifact',
    query="""

SELECT
    policy_id,
    COUNT(*) AS claim_count,
    SUM(reserve_amount) AS total_reserved_amount,
    SUM(paid_amount) AS total_paid_amount,
    MAX(loss_date) AS latest_loss_date,
    MAX(CASE WHEN claim_status = 'OPEN' THEN 1 ELSE 0 END) AS has_open_claim
FROM {{ queron.ref("policy_claim") }}
GROUP BY policy_id
    """,
)
def sql_93():
    pass

@queron.csv.egress(
    name='sql_141',
    path='exports/outputpolicy_coverage.csv',
    sql="""

    SELECT * FROM {{ queron.ref("policy_coverage") }}
    
    """,
    overwrite=True,
    header=True,
    delimiter=',',
)
def sql_141():
    pass

@queron.model.sql(
    name='sql_91',
    out='policy_customer_360',
    materialized='artifact',
    query="""

SELECT
    p.policy_id,
    p.policy_number,
    p.product_line,
    p.underwriting_company,
    p.status AS policy_status,
    p.effective_date,
    p.expiration_date,
    p.written_premium,
    p.deductible_amount,
    p.billing_plan,
    p.agent_code,
    p.risk_state,
    c.customer_number,
    c.first_name,
    c.last_name,
    c.birth_date,
    c.occupation,
    c.annual_income,
    c.preferred_language,
    c.address_line1,
    c.city,
    c.state_code AS customer_state,
    c.postal_code,
    c.phone_number,
    c.email_address,
    c.preferred_contact_channel,
    COALESCE(cs.coverage_count, 0) AS coverage_count,
    COALESCE(cs.total_coverage_premium, 0) AS total_coverage_premium,
    COALESCE(cs.has_optional_coverage, 0) AS has_optional_coverage,
    COALESCE(cl.claim_count, 0) AS claim_count,
    COALESCE(cl.total_reserved_amount, 0) AS total_reserved_amount,
    COALESCE(cl.total_paid_amount, 0) AS total_paid_amount,
    cl.latest_loss_date,
    COALESCE(cl.has_open_claim, 0) AS has_open_claim
FROM {{ queron.ref("policy_core") }} p
LEFT JOIN {{ queron.ref("customer_profile") }} c
  ON p.policy_number = c.policy_number
LEFT JOIN {{ queron.ref("coverage_summary") }} cs
  ON p.policy_id = cs.policy_id
LEFT JOIN {{ queron.ref("claim_summary") }} cl
  ON p.policy_id = cl.policy_id
    """,
)
def sql_91():
    pass

@queron.model.sql(
    name='sql_107',
    out='policy_servicing_queue',
    materialized='artifact',
    query="""

SELECT
    policy_number,
    customer_number,
    first_name,
    last_name,
    product_line,
    policy_status,
    written_premium,
    total_coverage_premium,
    claim_count,
    total_paid_amount,
    CASE
        WHEN has_open_claim = 1 THEN 'HIGH_TOUCH'
        WHEN claim_count >= 2 THEN 'WATCHLIST'
        WHEN written_premium >= 2500 THEN 'HIGH_VALUE'
        ELSE 'STANDARD'
    END AS servicing_segment
FROM {{ queron.ref("policy_customer_360") }}
    """,
)
def sql_107():
    pass

@queron.check.fail_if_count(
    name='sql_105',
    query="""

    SELECT COUNT(*)
    FROM {{ queron.ref("policy_servicing_queue") }}
    WHERE servicing_segment = 'HIGH_TOUCH'
    
    """,
    operator='<=',
    value=0,
)
def sql_105():
    pass

@queron.csv.egress(
    name='sql_133',
    path='exports/output.csv',
    sql="""

    SELECT * FROM {{ queron.ref("policy_customer_360") }}
    
    """,
    overwrite=True,
    header=True,
    delimiter=',',
)
def sql_133():
    pass

@queron.check.fail_if_true(
    name='sql_103',
    query="""

    SELECT EXISTS(
        SELECT 1
        FROM {{ queron.ref("policy_customer_360") }}
        WHERE policy_number IS NULL
           OR customer_number IS NULL
    )
    
    """,
)
def sql_103():
    pass

@queron.python.ingress(
    name='python_113',
    out='service_playbook',
)
def python_113():
    def load_service_playbook():
        import pandas as pd
        return pd.DataFrame([
            {"product_line": "AUTO", "queue_owner": "auto_team", "base_sla_hours": 4},
            {"product_line": "HOME", "queue_owner": "home_team", "base_sla_hours": 8},
            {"product_line": "UMBRELLA", "queue_owner": "specialty_team", "base_sla_hours": 12},
        ])
    return load_service_playbook()

@queron.csv.ingress(
    name='sql_117',
    out='vip_customers',
    path='local_files/vip_customers.csv',
    header=True,
    delimiter=',',
    columns={'customer_number': 'VARCHAR', 'vip_flag': 'BOOLEAN', 'vip_reason': 'VARCHAR'},
)
def sql_117():
    pass

@queron.jsonl.ingress(
    name='sql_115',
    out='servicing_overrides',
    path='local_files/servicing_overrides.jsonl',
)
def sql_115():
    pass

@queron.parquet.ingress(
    name='sql_119',
    out='segment_targets',
    path='local_files/segment_targets.parquet',
)
def sql_119():
    pass

@queron.model.sql(
    name='sql_121',
    out='policy_servicing_enriched',
    materialized='artifact',
    query="""

    SELECT
        q.policy_number,
        q.customer_number,
        q.first_name,
        q.last_name,
        q.product_line,
        q.policy_status,
        q.written_premium,
        q.total_coverage_premium,
        q.claim_count,
        q.total_paid_amount,
        q.servicing_segment,
        COALESCE(o.servicing_segment_override, q.servicing_segment) AS final_segment,
        COALESCE(v.vip_flag, FALSE) AS vip_flag,
        v.vip_reason,
        p.queue_owner,
        p.base_sla_hours,
        t.target_contact_hours
    FROM {{ queron.ref("policy_servicing_queue") }} q
    LEFT JOIN {{ queron.ref("vip_customers") }} v
      ON q.customer_number = v.customer_number
    LEFT JOIN {{ queron.ref("servicing_overrides") }} o
      ON q.policy_number = o.policy_number
    LEFT JOIN {{ queron.ref("service_playbook") }} p
      ON q.product_line = p.product_line
    LEFT JOIN {{ queron.ref("segment_targets") }} t
      ON COALESCE(o.servicing_segment_override, q.servicing_segment) = t.servicing_segment
    
    """,
)
def sql_121():
    pass

@queron.db2.egress(
    config='LOOMDB@localhost',
    name='sql_126',
    table='policy_servicing_enriched_load',
    sql="""

    SELECT *
    FROM {{ queron.ref("policy_servicing_enriched") }}
    
    """,
    mode='replace',
)
def sql_126():
    pass

@queron.postgres.egress(
    config='PostGres',
    name='sql_131',
    table='policy_servicing_enriched_load_postgres',
    sql="""

    SELECT *
    FROM {{ queron.ref("policy_servicing_enriched") }}
    
    """,
    mode='create_append',
)
def sql_131():
    pass

from pathlib import Path

postgres_config_factory = lambda: {
    'host': 'localhost',
    'port': 5432,
    'database': 'retail_db',
    'username': 'admin',
    'password': 'password123',
}
POSTGRES_RUNTIME_BINDING = queron.PostgresBinding(config_factory=postgres_config_factory)

loomdb_localhost_config_factory = lambda: {
    'host': 'localhost',
    'port': 50000,
    'database': 'LOOMDB',
    'username': 'db2inst1',
    'password': 'LoomDb2Pass123!',
}
LOOMDB_LOCALHOST_RUNTIME_BINDING = queron.Db2Binding(config_factory=loomdb_localhost_config_factory)

RUNTIME_BINDINGS = {
    'PostGres': POSTGRES_RUNTIME_BINDING,
    'LOOMDB@localhost': LOOMDB_LOCALHOST_RUNTIME_BINDING,
}

if __name__ == "__main__":
    result = queron.run_pipeline(
        Path(__file__).resolve(),
        connections_path="connections.yaml",
        runtime_bindings=RUNTIME_BINDINGS,
        clean_existing=True,
    )
    print(result)
